### ISSUE TITLE
Change ownership of your package

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/blogotext_ynh#1]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by frju365** [comment]
You can do that after you accept the invitation I send you to enter in the Yunohost-Apps orga. You will have write or admin right to your app, so, don't worry about rights. It's just to have just one place where users and packagers can find their apps and make teams.

**Comment by B4rb3rouss** [comment]
done

**Comment by frju365** [comment]
Thanks !
