### ISSUE TITLE
Alerte fonction PHP dépréciée suite au changement de version de PHP

### ISSUE THREAD

**Issue by bendia-** [YunoHost-Apps/blogotext_ynh#10]
Après la migration vers YNH 4, une alerte est apparue sur la page d'accueil. ` Deprecated: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /var/www/blogotext/inc/boot.php on line 200`

Il semble que le problème soit déjà [repéré et corrigé upstream](https://github.com/BlogoText/blogotext/pull/383) mais pas intégrée à la release 3.7.6 qui sert de base au paquet YNH.

**Comment by anto1ne** [comment]
Merci pour ce message bien documenté.

L'application a été faite pour stretch et je n'ai pas fait de test pour buster, je ne suis pas surpris que la migration apporte quelques surprises.

Espérons que blogotext sorte une version stable rapidement pour l'intégrer au package ynh
